// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/storage/storage.proto

package api_proto_storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorePortsReq struct {
	Ports                []*Port  `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePortsReq) Reset()         { *m = StorePortsReq{} }
func (m *StorePortsReq) String() string { return proto.CompactTextString(m) }
func (*StorePortsReq) ProtoMessage()    {}
func (*StorePortsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b1866f2fc1fa3a, []int{0}
}

func (m *StorePortsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePortsReq.Unmarshal(m, b)
}
func (m *StorePortsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePortsReq.Marshal(b, m, deterministic)
}
func (m *StorePortsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePortsReq.Merge(m, src)
}
func (m *StorePortsReq) XXX_Size() int {
	return xxx_messageInfo_StorePortsReq.Size(m)
}
func (m *StorePortsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePortsReq.DiscardUnknown(m)
}

var xxx_messageInfo_StorePortsReq proto.InternalMessageInfo

func (m *StorePortsReq) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

type StorePortsResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePortsResp) Reset()         { *m = StorePortsResp{} }
func (m *StorePortsResp) String() string { return proto.CompactTextString(m) }
func (*StorePortsResp) ProtoMessage()    {}
func (*StorePortsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b1866f2fc1fa3a, []int{1}
}

func (m *StorePortsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePortsResp.Unmarshal(m, b)
}
func (m *StorePortsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePortsResp.Marshal(b, m, deterministic)
}
func (m *StorePortsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePortsResp.Merge(m, src)
}
func (m *StorePortsResp) XXX_Size() int {
	return xxx_messageInfo_StorePortsResp.Size(m)
}
func (m *StorePortsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePortsResp.DiscardUnknown(m)
}

var xxx_messageInfo_StorePortsResp proto.InternalMessageInfo

type Port struct {
	Key                  string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string    `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country              string    `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Alias                []string  `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions              []string  `protobuf:"bytes,6,rep,name=regions,proto3" json:"regions,omitempty"`
	Coordinates          []float64 `protobuf:"fixed64,7,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Province             string    `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	Tz                   string    `protobuf:"bytes,9,opt,name=tz,proto3" json:"tz,omitempty"`
	Unlocs               []string  `protobuf:"bytes,10,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	Code                 string    `protobuf:"bytes,11,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b1866f2fc1fa3a, []int{2}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Port) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTz() string {
	if m != nil {
		return m.Tz
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *Port) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*StorePortsReq)(nil), "api.proto.storage.StorePortsReq")
	proto.RegisterType((*StorePortsResp)(nil), "api.proto.storage.StorePortsResp")
	proto.RegisterType((*Port)(nil), "api.proto.storage.Port")
}

func init() {
	proto.RegisterFile("api/proto/storage/storage.proto", fileDescriptor_b4b1866f2fc1fa3a)
}

var fileDescriptor_b4b1866f2fc1fa3a = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0xdd, 0xfe, 0x9d, 0x62, 0xa9, 0x83, 0xe8, 0xd0, 0x8b, 0xb1, 0xa7, 0xbd, 0xb8,
	0x85, 0x7a, 0xf7, 0x33, 0xe8, 0xf6, 0xea, 0x25, 0x6e, 0x43, 0x09, 0xd6, 0x4c, 0x4c, 0x52, 0xa1,
	0x3d, 0xfb, 0xc1, 0x25, 0xd9, 0x56, 0x2b, 0x0a, 0x9e, 0xf2, 0xde, 0x6f, 0xde, 0x30, 0xcc, 0x04,
	0xae, 0xa5, 0xd5, 0x73, 0xeb, 0x38, 0xf0, 0xdc, 0x07, 0x76, 0x72, 0xad, 0x8e, 0x6f, 0x95, 0x28,
	0x9e, 0x4b, 0xab, 0x5b, 0x59, 0x1d, 0x0a, 0xb3, 0x7b, 0x38, 0x5b, 0x06, 0x76, 0xea, 0x81, 0x5d,
	0xf0, 0xb5, 0x7a, 0xc3, 0x5b, 0xe8, 0xda, 0xa8, 0x29, 0x13, 0x45, 0x39, 0x5a, 0x5c, 0x55, 0xbf,
	0x7a, 0xaa, 0x98, 0xad, 0xdb, 0xd4, 0x6c, 0x02, 0xe3, 0xd3, 0x7e, 0x6f, 0x67, 0x1f, 0x39, 0x74,
	0xa2, 0xc3, 0x09, 0x14, 0x2f, 0x6a, 0x47, 0x99, 0xc8, 0xca, 0x61, 0x1d, 0x25, 0x22, 0x74, 0x8c,
	0x7c, 0x55, 0x94, 0x27, 0x94, 0x74, 0x64, 0x8d, 0x0e, 0x3b, 0x2a, 0x5a, 0x16, 0x35, 0x12, 0xf4,
	0x1b, 0xde, 0x9a, 0xe0, 0x76, 0xd4, 0x49, 0xf8, 0x68, 0xf1, 0x02, 0xba, 0x72, 0xa3, 0xa5, 0xa7,
	0xae, 0x28, 0xca, 0x61, 0xdd, 0x9a, 0x98, 0x77, 0x6a, 0xad, 0xd9, 0x78, 0xea, 0x25, 0x7e, 0xb4,
	0x28, 0x60, 0xd4, 0x30, 0xbb, 0x95, 0x36, 0x32, 0x28, 0x4f, 0x7d, 0x51, 0x94, 0x59, 0x7d, 0x8a,
	0x70, 0x0a, 0x03, 0xeb, 0xf8, 0x5d, 0x9b, 0x46, 0xd1, 0x20, 0x0d, 0xfb, 0xf2, 0x38, 0x86, 0x3c,
	0xec, 0x69, 0x98, 0x68, 0x1e, 0xf6, 0x78, 0x09, 0xbd, 0xad, 0xd9, 0x70, 0xe3, 0x09, 0xd2, 0x98,
	0x83, 0x4b, 0x3b, 0xf0, 0x4a, 0xd1, 0xe8, 0xb0, 0x03, 0xaf, 0xd4, 0xe2, 0x09, 0xfa, 0xcb, 0xf6,
	0x5e, 0xf8, 0x08, 0xf0, 0x7d, 0x23, 0x14, 0x7f, 0x5c, 0xf4, 0xc7, 0x17, 0x4c, 0x6f, 0xfe, 0x49,
	0x78, 0xfb, 0xdc, 0x4b, 0xd5, 0xbb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x27, 0x18, 0x0e,
	0xf3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	StorePorts(ctx context.Context, in *StorePortsReq, opts ...grpc.CallOption) (*StorePortsResp, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) StorePorts(ctx context.Context, in *StorePortsReq, opts ...grpc.CallOption) (*StorePortsResp, error) {
	out := new(StorePortsResp)
	err := c.cc.Invoke(ctx, "/api.proto.storage.Storage/StorePorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	StorePorts(context.Context, *StorePortsReq) (*StorePortsResp, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) StorePorts(ctx context.Context, req *StorePortsReq) (*StorePortsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorePorts not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_StorePorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePortsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).StorePorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.storage.Storage/StorePorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).StorePorts(ctx, req.(*StorePortsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StorePorts",
			Handler:    _Storage_StorePorts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/storage/storage.proto",
}
