// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/storage/storage.proto

package api_proto_storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorePortsReq struct {
	Ports                []*Port  `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePortsReq) Reset()         { *m = StorePortsReq{} }
func (m *StorePortsReq) String() string { return proto.CompactTextString(m) }
func (*StorePortsReq) ProtoMessage()    {}
func (*StorePortsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{0}
}

func (m *StorePortsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePortsReq.Unmarshal(m, b)
}
func (m *StorePortsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePortsReq.Marshal(b, m, deterministic)
}
func (m *StorePortsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePortsReq.Merge(m, src)
}
func (m *StorePortsReq) XXX_Size() int {
	return xxx_messageInfo_StorePortsReq.Size(m)
}
func (m *StorePortsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePortsReq.DiscardUnknown(m)
}

var xxx_messageInfo_StorePortsReq proto.InternalMessageInfo

func (m *StorePortsReq) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

type StorePortsResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePortsResp) Reset()         { *m = StorePortsResp{} }
func (m *StorePortsResp) String() string { return proto.CompactTextString(m) }
func (*StorePortsResp) ProtoMessage()    {}
func (*StorePortsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{1}
}

func (m *StorePortsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePortsResp.Unmarshal(m, b)
}
func (m *StorePortsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePortsResp.Marshal(b, m, deterministic)
}
func (m *StorePortsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePortsResp.Merge(m, src)
}
func (m *StorePortsResp) XXX_Size() int {
	return xxx_messageInfo_StorePortsResp.Size(m)
}
func (m *StorePortsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePortsResp.DiscardUnknown(m)
}

var xxx_messageInfo_StorePortsResp proto.InternalMessageInfo

type GetPortReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortReq) Reset()         { *m = GetPortReq{} }
func (m *GetPortReq) String() string { return proto.CompactTextString(m) }
func (*GetPortReq) ProtoMessage()    {}
func (*GetPortReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{2}
}

func (m *GetPortReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortReq.Unmarshal(m, b)
}
func (m *GetPortReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortReq.Marshal(b, m, deterministic)
}
func (m *GetPortReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortReq.Merge(m, src)
}
func (m *GetPortReq) XXX_Size() int {
	return xxx_messageInfo_GetPortReq.Size(m)
}
func (m *GetPortReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortReq proto.InternalMessageInfo

func (m *GetPortReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetPortResp struct {
	Port                 *Port    `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortResp) Reset()         { *m = GetPortResp{} }
func (m *GetPortResp) String() string { return proto.CompactTextString(m) }
func (*GetPortResp) ProtoMessage()    {}
func (*GetPortResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{3}
}

func (m *GetPortResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortResp.Unmarshal(m, b)
}
func (m *GetPortResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortResp.Marshal(b, m, deterministic)
}
func (m *GetPortResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortResp.Merge(m, src)
}
func (m *GetPortResp) XXX_Size() int {
	return xxx_messageInfo_GetPortResp.Size(m)
}
func (m *GetPortResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortResp proto.InternalMessageInfo

func (m *GetPortResp) GetPort() *Port {
	if m != nil {
		return m.Port
	}
	return nil
}

type Port struct {
	Key                  string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string    `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country              string    `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Alias                []string  `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions              []string  `protobuf:"bytes,6,rep,name=regions,proto3" json:"regions,omitempty"`
	Coordinates          []float64 `protobuf:"fixed64,7,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Province             string    `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	Tz                   string    `protobuf:"bytes,9,opt,name=tz,proto3" json:"tz,omitempty"`
	Unlocs               []string  `protobuf:"bytes,10,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	Code                 string    `protobuf:"bytes,11,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{4}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Port) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTz() string {
	if m != nil {
		return m.Tz
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *Port) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*StorePortsReq)(nil), "api.proto.storage.StorePortsReq")
	proto.RegisterType((*StorePortsResp)(nil), "api.proto.storage.StorePortsResp")
	proto.RegisterType((*GetPortReq)(nil), "api.proto.storage.GetPortReq")
	proto.RegisterType((*GetPortResp)(nil), "api.proto.storage.GetPortResp")
	proto.RegisterType((*Port)(nil), "api.proto.storage.Port")
}

func init() {
	proto.RegisterFile("proto/storage/storage.proto", fileDescriptor_c87989e2875259d4)
}

var fileDescriptor_c87989e2875259d4 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xd3, 0x3f, 0x50, 0x98, 0xe6, 0x25, 0xbc, 0x13, 0xa3, 0x1b, 0x8c, 0xa4, 0xf6, 0xd4,
	0xc4, 0x58, 0x13, 0xbc, 0x79, 0xf0, 0xaa, 0x47, 0x2d, 0x9f, 0xa0, 0x96, 0x0d, 0x69, 0xc4, 0xee,
	0xb2, 0xbb, 0x98, 0xc0, 0xd9, 0xcf, 0xe2, 0xe7, 0x34, 0x3b, 0x6d, 0x01, 0x03, 0xc1, 0xd3, 0x3e,
	0xcf, 0x33, 0xbf, 0xdd, 0xc9, 0xce, 0xc0, 0xa5, 0x54, 0xc2, 0x88, 0x3b, 0x6d, 0x84, 0xca, 0xe7,
	0xbc, 0x3d, 0x53, 0x4a, 0xf1, 0x7f, 0x2e, 0xcb, 0x5a, 0xa6, 0x4d, 0x21, 0x7e, 0x84, 0x7f, 0x53,
	0x23, 0x14, 0x7f, 0x11, 0xca, 0xe8, 0x8c, 0x2f, 0xf1, 0x16, 0x3a, 0xd2, 0x6a, 0xe6, 0x44, 0x5e,
	0x12, 0x4e, 0x2e, 0xd2, 0x83, 0x3b, 0xa9, 0x65, 0xb3, 0x9a, 0x8a, 0x87, 0x30, 0xd8, 0xbf, 0xaf,
	0x65, 0x3c, 0x06, 0x78, 0xe2, 0x86, 0x18, 0xbe, 0xc4, 0x21, 0x78, 0xef, 0x7c, 0xcd, 0x9c, 0xc8,
	0x49, 0xfa, 0x99, 0x95, 0xf1, 0x03, 0x84, 0xdb, 0xba, 0x96, 0x78, 0x03, 0xbe, 0x7d, 0x89, 0x88,
	0x13, 0xed, 0x08, 0x8a, 0xbf, 0x5c, 0xf0, 0xad, 0x3d, 0x7c, 0x16, 0x11, 0xfc, 0x2a, 0xff, 0xe0,
	0xcc, 0xa5, 0x88, 0xb4, 0xcd, 0x8a, 0xd2, 0xac, 0x99, 0x57, 0x67, 0x56, 0x23, 0x83, 0xa0, 0x10,
	0xab, 0xca, 0xa8, 0x35, 0xf3, 0x29, 0x6e, 0x2d, 0x9e, 0x41, 0x27, 0x5f, 0x94, 0xb9, 0x66, 0x9d,
	0xc8, 0x4b, 0xfa, 0x59, 0x6d, 0x2c, 0xaf, 0xf8, 0xbc, 0x14, 0x95, 0x66, 0x5d, 0xca, 0x5b, 0x8b,
	0x11, 0x84, 0x85, 0x10, 0x6a, 0x56, 0x56, 0xb9, 0xe1, 0x9a, 0x05, 0x91, 0x97, 0x38, 0xd9, 0x7e,
	0x84, 0x23, 0xe8, 0x49, 0x25, 0x3e, 0xcb, 0xaa, 0xe0, 0xac, 0x47, 0xcd, 0xb6, 0x1e, 0x07, 0xe0,
	0x9a, 0x0d, 0xeb, 0x53, 0xea, 0x9a, 0x0d, 0x9e, 0x43, 0x77, 0x55, 0x2d, 0x44, 0xa1, 0x19, 0x50,
	0x9b, 0xc6, 0xd1, 0x1f, 0xc4, 0x8c, 0xb3, 0xb0, 0xf9, 0x83, 0x98, 0xf1, 0xc9, 0xb7, 0x03, 0xc1,
	0xb4, 0x9e, 0x0e, 0xbe, 0x02, 0xec, 0x16, 0x80, 0xd1, 0x91, 0xf9, 0xfd, 0xda, 0xef, 0xe8, 0xfa,
	0x0f, 0x42, 0x4b, 0x7c, 0x86, 0xa0, 0xd9, 0x10, 0x5e, 0x1d, 0xa1, 0x77, 0xdb, 0x1d, 0x8d, 0x4f,
	0x95, 0xb5, 0x7c, 0xeb, 0x52, 0xe9, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x24, 0x36, 0xe2, 0xe2,
	0x96, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	StorePorts(ctx context.Context, in *StorePortsReq, opts ...grpc.CallOption) (*StorePortsResp, error)
	GetPort(ctx context.Context, in *GetPortReq, opts ...grpc.CallOption) (*GetPortResp, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) StorePorts(ctx context.Context, in *StorePortsReq, opts ...grpc.CallOption) (*StorePortsResp, error) {
	out := new(StorePortsResp)
	err := c.cc.Invoke(ctx, "/api.proto.storage.Storage/StorePorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetPort(ctx context.Context, in *GetPortReq, opts ...grpc.CallOption) (*GetPortResp, error) {
	out := new(GetPortResp)
	err := c.cc.Invoke(ctx, "/api.proto.storage.Storage/GetPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	StorePorts(context.Context, *StorePortsReq) (*StorePortsResp, error)
	GetPort(context.Context, *GetPortReq) (*GetPortResp, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) StorePorts(ctx context.Context, req *StorePortsReq) (*StorePortsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorePorts not implemented")
}
func (*UnimplementedStorageServer) GetPort(ctx context.Context, req *GetPortReq) (*GetPortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPort not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_StorePorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePortsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).StorePorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.storage.Storage/StorePorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).StorePorts(ctx, req.(*StorePortsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.storage.Storage/GetPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetPort(ctx, req.(*GetPortReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StorePorts",
			Handler:    _Storage_StorePorts_Handler,
		},
		{
			MethodName: "GetPort",
			Handler:    _Storage_GetPort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/storage/storage.proto",
}
