// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/processor/processor.proto

package api_proto_processor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataType int32

const (
	DataType_PORT DataType = 0
)

var DataType_name = map[int32]string{
	0: "PORT",
}

var DataType_value = map[string]int32{
	"PORT": 0,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6d0a7cd8e8f922a1, []int{0}
}

type ProcessFileReq struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Type                 DataType `protobuf:"varint,2,opt,name=type,proto3,enum=api.proto.processor.DataType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessFileReq) Reset()         { *m = ProcessFileReq{} }
func (m *ProcessFileReq) String() string { return proto.CompactTextString(m) }
func (*ProcessFileReq) ProtoMessage()    {}
func (*ProcessFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d0a7cd8e8f922a1, []int{0}
}

func (m *ProcessFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessFileReq.Unmarshal(m, b)
}
func (m *ProcessFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessFileReq.Marshal(b, m, deterministic)
}
func (m *ProcessFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessFileReq.Merge(m, src)
}
func (m *ProcessFileReq) XXX_Size() int {
	return xxx_messageInfo_ProcessFileReq.Size(m)
}
func (m *ProcessFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessFileReq proto.InternalMessageInfo

func (m *ProcessFileReq) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ProcessFileReq) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_PORT
}

type ProcessFileResp struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessFileResp) Reset()         { *m = ProcessFileResp{} }
func (m *ProcessFileResp) String() string { return proto.CompactTextString(m) }
func (*ProcessFileResp) ProtoMessage()    {}
func (*ProcessFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d0a7cd8e8f922a1, []int{1}
}

func (m *ProcessFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessFileResp.Unmarshal(m, b)
}
func (m *ProcessFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessFileResp.Marshal(b, m, deterministic)
}
func (m *ProcessFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessFileResp.Merge(m, src)
}
func (m *ProcessFileResp) XXX_Size() int {
	return xxx_messageInfo_ProcessFileResp.Size(m)
}
func (m *ProcessFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessFileResp proto.InternalMessageInfo

func (m *ProcessFileResp) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type GetProgressReq struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProgressReq) Reset()         { *m = GetProgressReq{} }
func (m *GetProgressReq) String() string { return proto.CompactTextString(m) }
func (*GetProgressReq) ProtoMessage()    {}
func (*GetProgressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d0a7cd8e8f922a1, []int{2}
}

func (m *GetProgressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProgressReq.Unmarshal(m, b)
}
func (m *GetProgressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProgressReq.Marshal(b, m, deterministic)
}
func (m *GetProgressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProgressReq.Merge(m, src)
}
func (m *GetProgressReq) XXX_Size() int {
	return xxx_messageInfo_GetProgressReq.Size(m)
}
func (m *GetProgressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProgressReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProgressReq proto.InternalMessageInfo

func (m *GetProgressReq) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type GetProgressResp struct {
	ItemsProcessed       int64    `protobuf:"varint,1,opt,name=items_processed,json=itemsProcessed,proto3" json:"items_processed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProgressResp) Reset()         { *m = GetProgressResp{} }
func (m *GetProgressResp) String() string { return proto.CompactTextString(m) }
func (*GetProgressResp) ProtoMessage()    {}
func (*GetProgressResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d0a7cd8e8f922a1, []int{3}
}

func (m *GetProgressResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProgressResp.Unmarshal(m, b)
}
func (m *GetProgressResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProgressResp.Marshal(b, m, deterministic)
}
func (m *GetProgressResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProgressResp.Merge(m, src)
}
func (m *GetProgressResp) XXX_Size() int {
	return xxx_messageInfo_GetProgressResp.Size(m)
}
func (m *GetProgressResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProgressResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProgressResp proto.InternalMessageInfo

func (m *GetProgressResp) GetItemsProcessed() int64 {
	if m != nil {
		return m.ItemsProcessed
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.proto.processor.DataType", DataType_name, DataType_value)
	proto.RegisterType((*ProcessFileReq)(nil), "api.proto.processor.ProcessFileReq")
	proto.RegisterType((*ProcessFileResp)(nil), "api.proto.processor.ProcessFileResp")
	proto.RegisterType((*GetProgressReq)(nil), "api.proto.processor.GetProgressReq")
	proto.RegisterType((*GetProgressResp)(nil), "api.proto.processor.GetProgressResp")
}

func init() {
	proto.RegisterFile("api/proto/processor/processor.proto", fileDescriptor_6d0a7cd8e8f922a1)
}

var fileDescriptor_6d0a7cd8e8f922a1 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x07, 0x91, 0xc9, 0xa9, 0xc5, 0xc5, 0xf9, 0x45, 0x08, 0x96, 0x1e,
	0x58, 0x46, 0x48, 0x38, 0xb1, 0x20, 0x13, 0xc2, 0xd4, 0x83, 0x4b, 0x29, 0xc5, 0x73, 0xf1, 0x05,
	0x40, 0x38, 0x6e, 0x99, 0x39, 0xa9, 0x41, 0xa9, 0x85, 0x42, 0x52, 0x5c, 0x1c, 0x69, 0x99, 0x39,
	0xa9, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x90, 0x21,
	0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0xac, 0x1e, 0x16,
	0x13, 0xf5, 0x5c, 0x12, 0x4b, 0x12, 0x43, 0x2a, 0x0b, 0x52, 0x83, 0xc0, 0x4a, 0x95, 0x34, 0xb8,
	0xf8, 0x51, 0x2c, 0x28, 0x2e, 0x10, 0x12, 0xe5, 0x62, 0xcb, 0xca, 0x4f, 0x8a, 0xcf, 0x4c, 0x81,
	0x9a, 0xcf, 0x9a, 0x95, 0x9f, 0xe4, 0x99, 0xa2, 0xa4, 0xce, 0xc5, 0xe7, 0x9e, 0x5a, 0x12, 0x50,
	0x94, 0x9f, 0x5e, 0x94, 0x5a, 0x5c, 0x0c, 0x72, 0x0a, 0x0e, 0x85, 0x56, 0x5c, 0xfc, 0x28, 0x0a,
	0x8b, 0x0b, 0x84, 0xd4, 0xb9, 0xf8, 0x33, 0x4b, 0x52, 0x73, 0x8b, 0xe3, 0xa1, 0xee, 0x48, 0x85,
	0x68, 0x61, 0x0e, 0xe2, 0x03, 0x0b, 0x07, 0xc0, 0x44, 0xb5, 0x44, 0xb8, 0x38, 0x60, 0x0e, 0x14,
	0xe2, 0xe0, 0x62, 0x09, 0xf0, 0x0f, 0x0a, 0x11, 0x60, 0x30, 0x4a, 0xe7, 0xe2, 0x0c, 0x80, 0x79,
	0x40, 0x28, 0x8a, 0x8b, 0x1b, 0xc9, 0xc5, 0x42, 0xca, 0x58, 0x7d, 0x89, 0x1a, 0x68, 0x52, 0x2a,
	0x84, 0x15, 0x15, 0x17, 0x28, 0x31, 0x24, 0xb1, 0x81, 0x95, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xde, 0x17, 0x9a, 0xfc, 0xb1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProcessorClient is the client API for Processor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessorClient interface {
	ProcessFile(ctx context.Context, in *ProcessFileReq, opts ...grpc.CallOption) (*ProcessFileResp, error)
}

type processorClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessorClient(cc grpc.ClientConnInterface) ProcessorClient {
	return &processorClient{cc}
}

func (c *processorClient) ProcessFile(ctx context.Context, in *ProcessFileReq, opts ...grpc.CallOption) (*ProcessFileResp, error) {
	out := new(ProcessFileResp)
	err := c.cc.Invoke(ctx, "/api.proto.processor.Processor/ProcessFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessorServer is the server API for Processor service.
type ProcessorServer interface {
	ProcessFile(context.Context, *ProcessFileReq) (*ProcessFileResp, error)
}

// UnimplementedProcessorServer can be embedded to have forward compatible implementations.
type UnimplementedProcessorServer struct {
}

func (*UnimplementedProcessorServer) ProcessFile(ctx context.Context, req *ProcessFileReq) (*ProcessFileResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessFile not implemented")
}

func RegisterProcessorServer(s *grpc.Server, srv ProcessorServer) {
	s.RegisterService(&_Processor_serviceDesc, srv)
}

func _Processor_ProcessFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).ProcessFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.processor.Processor/ProcessFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).ProcessFile(ctx, req.(*ProcessFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Processor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.processor.Processor",
	HandlerType: (*ProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessFile",
			Handler:    _Processor_ProcessFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/processor/processor.proto",
}
