// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/processor/processor.proto

package api_proto_processor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataType int32

const (
	DataType_PORT DataType = 0
)

var DataType_name = map[int32]string{
	0: "PORT",
}

var DataType_value = map[string]int32{
	"PORT": 0,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed2a982c06e67717, []int{0}
}

type ProcessFileReq struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Type                 DataType `protobuf:"varint,2,opt,name=type,proto3,enum=api.proto.processor.DataType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessFileReq) Reset()         { *m = ProcessFileReq{} }
func (m *ProcessFileReq) String() string { return proto.CompactTextString(m) }
func (*ProcessFileReq) ProtoMessage()    {}
func (*ProcessFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed2a982c06e67717, []int{0}
}

func (m *ProcessFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessFileReq.Unmarshal(m, b)
}
func (m *ProcessFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessFileReq.Marshal(b, m, deterministic)
}
func (m *ProcessFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessFileReq.Merge(m, src)
}
func (m *ProcessFileReq) XXX_Size() int {
	return xxx_messageInfo_ProcessFileReq.Size(m)
}
func (m *ProcessFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessFileReq proto.InternalMessageInfo

func (m *ProcessFileReq) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ProcessFileReq) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_PORT
}

type ProcessFileResp struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessFileResp) Reset()         { *m = ProcessFileResp{} }
func (m *ProcessFileResp) String() string { return proto.CompactTextString(m) }
func (*ProcessFileResp) ProtoMessage()    {}
func (*ProcessFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed2a982c06e67717, []int{1}
}

func (m *ProcessFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessFileResp.Unmarshal(m, b)
}
func (m *ProcessFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessFileResp.Marshal(b, m, deterministic)
}
func (m *ProcessFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessFileResp.Merge(m, src)
}
func (m *ProcessFileResp) XXX_Size() int {
	return xxx_messageInfo_ProcessFileResp.Size(m)
}
func (m *ProcessFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessFileResp proto.InternalMessageInfo

func (m *ProcessFileResp) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type GetProgressReq struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProgressReq) Reset()         { *m = GetProgressReq{} }
func (m *GetProgressReq) String() string { return proto.CompactTextString(m) }
func (*GetProgressReq) ProtoMessage()    {}
func (*GetProgressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed2a982c06e67717, []int{2}
}

func (m *GetProgressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProgressReq.Unmarshal(m, b)
}
func (m *GetProgressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProgressReq.Marshal(b, m, deterministic)
}
func (m *GetProgressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProgressReq.Merge(m, src)
}
func (m *GetProgressReq) XXX_Size() int {
	return xxx_messageInfo_GetProgressReq.Size(m)
}
func (m *GetProgressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProgressReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProgressReq proto.InternalMessageInfo

func (m *GetProgressReq) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type GetProgressResp struct {
	ItemsProcessed       int64    `protobuf:"varint,1,opt,name=items_processed,json=itemsProcessed,proto3" json:"items_processed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProgressResp) Reset()         { *m = GetProgressResp{} }
func (m *GetProgressResp) String() string { return proto.CompactTextString(m) }
func (*GetProgressResp) ProtoMessage()    {}
func (*GetProgressResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed2a982c06e67717, []int{3}
}

func (m *GetProgressResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProgressResp.Unmarshal(m, b)
}
func (m *GetProgressResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProgressResp.Marshal(b, m, deterministic)
}
func (m *GetProgressResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProgressResp.Merge(m, src)
}
func (m *GetProgressResp) XXX_Size() int {
	return xxx_messageInfo_GetProgressResp.Size(m)
}
func (m *GetProgressResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProgressResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProgressResp proto.InternalMessageInfo

func (m *GetProgressResp) GetItemsProcessed() int64 {
	if m != nil {
		return m.ItemsProcessed
	}
	return 0
}

type GetPortReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortReq) Reset()         { *m = GetPortReq{} }
func (m *GetPortReq) String() string { return proto.CompactTextString(m) }
func (*GetPortReq) ProtoMessage()    {}
func (*GetPortReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed2a982c06e67717, []int{4}
}

func (m *GetPortReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortReq.Unmarshal(m, b)
}
func (m *GetPortReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortReq.Marshal(b, m, deterministic)
}
func (m *GetPortReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortReq.Merge(m, src)
}
func (m *GetPortReq) XXX_Size() int {
	return xxx_messageInfo_GetPortReq.Size(m)
}
func (m *GetPortReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortReq proto.InternalMessageInfo

func (m *GetPortReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetPortResp struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortResp) Reset()         { *m = GetPortResp{} }
func (m *GetPortResp) String() string { return proto.CompactTextString(m) }
func (*GetPortResp) ProtoMessage()    {}
func (*GetPortResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed2a982c06e67717, []int{5}
}

func (m *GetPortResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortResp.Unmarshal(m, b)
}
func (m *GetPortResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortResp.Marshal(b, m, deterministic)
}
func (m *GetPortResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortResp.Merge(m, src)
}
func (m *GetPortResp) XXX_Size() int {
	return xxx_messageInfo_GetPortResp.Size(m)
}
func (m *GetPortResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortResp proto.InternalMessageInfo

func (m *GetPortResp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.proto.processor.DataType", DataType_name, DataType_value)
	proto.RegisterType((*ProcessFileReq)(nil), "api.proto.processor.ProcessFileReq")
	proto.RegisterType((*ProcessFileResp)(nil), "api.proto.processor.ProcessFileResp")
	proto.RegisterType((*GetProgressReq)(nil), "api.proto.processor.GetProgressReq")
	proto.RegisterType((*GetProgressResp)(nil), "api.proto.processor.GetProgressResp")
	proto.RegisterType((*GetPortReq)(nil), "api.proto.processor.GetPortReq")
	proto.RegisterType((*GetPortResp)(nil), "api.proto.processor.GetPortResp")
}

func init() {
	proto.RegisterFile("proto/processor/processor.proto", fileDescriptor_ed2a982c06e67717)
}

var fileDescriptor_ed2a982c06e67717 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0xad, 0xb5, 0x9d, 0x42, 0x52, 0x56, 0x85, 0x12, 0xd0, 0x84, 0x28, 0x34, 0x78,
	0x88, 0x58, 0x6f, 0x9e, 0x45, 0x11, 0x04, 0x43, 0xe8, 0xc1, 0x5b, 0x48, 0xec, 0x28, 0x5b, 0x5b,
	0x77, 0xdd, 0xd9, 0x4b, 0x7e, 0x97, 0x7f, 0x50, 0xf2, 0x59, 0x83, 0x51, 0x6f, 0x33, 0xf3, 0x3e,
	0xf3, 0xf5, 0x82, 0x23, 0x95, 0xd0, 0xe2, 0x42, 0x2a, 0xf1, 0x8c, 0x44, 0x42, 0x6d, 0xa3, 0xa0,
	0x50, 0xd8, 0x41, 0x22, 0x79, 0x19, 0x06, 0x8d, 0xe4, 0xc5, 0x60, 0x86, 0x65, 0x72, 0xcb, 0xd7,
	0x18, 0xe1, 0x07, 0xb3, 0x61, 0xf8, 0xc2, 0xd7, 0xf8, 0x9e, 0x6c, 0x70, 0x6a, 0xb8, 0x86, 0x3f,
	0x8a, 0x9a, 0x9c, 0x5d, 0x42, 0x5f, 0x67, 0x12, 0xa7, 0xbb, 0xae, 0xe1, 0x9b, 0xf3, 0xe3, 0xa0,
	0x63, 0x62, 0x70, 0x93, 0xe8, 0x64, 0x91, 0x49, 0x8c, 0x0a, 0xd4, 0xf3, 0xc1, 0x6a, 0x2d, 0x20,
	0xc9, 0x8e, 0x60, 0xb0, 0x12, 0x69, 0xcc, 0x97, 0xd5, 0xfc, 0xbd, 0x95, 0x48, 0xef, 0x97, 0xde,
	0x0c, 0xcc, 0x3b, 0xd4, 0xa1, 0x12, 0xaf, 0x0a, 0x89, 0xf2, 0x53, 0x7e, 0x01, 0xaf, 0xc1, 0x6a,
	0x81, 0x24, 0xd9, 0x0c, 0x2c, 0xae, 0x71, 0x43, 0x71, 0x75, 0x07, 0x96, 0x2d, 0xbd, 0xc8, 0x2c,
	0xca, 0x61, 0x5d, 0xf5, 0x4e, 0x00, 0xf2, 0x5e, 0xa1, 0x74, 0xbe, 0x60, 0x02, 0xbd, 0x37, 0xcc,
	0xaa, 0xe9, 0x79, 0xe8, 0x39, 0x30, 0x6e, 0x74, 0x92, 0x3f, 0x81, 0xf3, 0x43, 0x18, 0xd6, 0x1f,
	0xb2, 0x21, 0xf4, 0xc3, 0xc7, 0x68, 0x31, 0xd9, 0x99, 0x7f, 0x1a, 0x30, 0x0a, 0x6b, 0x0b, 0xd8,
	0x13, 0x8c, 0xbf, 0xfd, 0xcc, 0x4e, 0x3b, 0x7d, 0x6a, 0xdb, 0x6e, 0x9f, 0xfd, 0x0f, 0x91, 0x64,
	0x0f, 0xb0, 0x5f, 0x9d, 0xc7, 0x9c, 0xce, 0x86, 0xed, 0x73, 0xb6, 0xfb, 0x37, 0x40, 0x32, 0x1d,
	0x14, 0xe2, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xe3, 0x60, 0xc6, 0x3b, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProcessorClient is the client API for Processor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessorClient interface {
	ProcessFile(ctx context.Context, in *ProcessFileReq, opts ...grpc.CallOption) (*ProcessFileResp, error)
	// rpc GetProgress(GetProgressReq) returns (GetProgressResp);
	// rpc StopProcessing(StopProcessingReq) returns(StopProcessingResp);
	GetPort(ctx context.Context, in *GetPortReq, opts ...grpc.CallOption) (*GetPortResp, error)
}

type processorClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessorClient(cc grpc.ClientConnInterface) ProcessorClient {
	return &processorClient{cc}
}

func (c *processorClient) ProcessFile(ctx context.Context, in *ProcessFileReq, opts ...grpc.CallOption) (*ProcessFileResp, error) {
	out := new(ProcessFileResp)
	err := c.cc.Invoke(ctx, "/api.proto.processor.Processor/ProcessFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorClient) GetPort(ctx context.Context, in *GetPortReq, opts ...grpc.CallOption) (*GetPortResp, error) {
	out := new(GetPortResp)
	err := c.cc.Invoke(ctx, "/api.proto.processor.Processor/GetPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessorServer is the server API for Processor service.
type ProcessorServer interface {
	ProcessFile(context.Context, *ProcessFileReq) (*ProcessFileResp, error)
	// rpc GetProgress(GetProgressReq) returns (GetProgressResp);
	// rpc StopProcessing(StopProcessingReq) returns(StopProcessingResp);
	GetPort(context.Context, *GetPortReq) (*GetPortResp, error)
}

// UnimplementedProcessorServer can be embedded to have forward compatible implementations.
type UnimplementedProcessorServer struct {
}

func (*UnimplementedProcessorServer) ProcessFile(ctx context.Context, req *ProcessFileReq) (*ProcessFileResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessFile not implemented")
}
func (*UnimplementedProcessorServer) GetPort(ctx context.Context, req *GetPortReq) (*GetPortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPort not implemented")
}

func RegisterProcessorServer(s *grpc.Server, srv ProcessorServer) {
	s.RegisterService(&_Processor_serviceDesc, srv)
}

func _Processor_ProcessFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).ProcessFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.processor.Processor/ProcessFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).ProcessFile(ctx, req.(*ProcessFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processor_GetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).GetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.processor.Processor/GetPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).GetPort(ctx, req.(*GetPortReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Processor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.processor.Processor",
	HandlerType: (*ProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessFile",
			Handler:    _Processor_ProcessFile_Handler,
		},
		{
			MethodName: "GetPort",
			Handler:    _Processor_GetPort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/processor/processor.proto",
}
